name: Update Data

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository 
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
      
      - name: install python packages
        run: |
          cd data
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: execute data update script
        env: 
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          cd data
          python process_data.py
        
          

    
